Feat: Access page backend and frontend
AJSahagun/FRAMES-remastered pull request #34
Opened 2024-11-26 06:31 UTC by AJSahagun

2024-11-26 14:29 UTC, marius-hernandez commented on frontend/src/pages/access/hooks/useBulkRequest.ts
> +    }, 60*30* 1000); // Every 1 hour
final na every 30 mins ang bulk request ng history?

2024-11-26 14:29 UTC, marius-hernandez requested changes
LGTM

2024-11-27 21:38 UTC, AJSahagun commented
Check reply

2024-11-28 03:48 UTC, marius-hernandez approved these changes
LGTM

2024-11-28 16:02 UTC, gonzalestrisha approved these changes
good

2024-11-28 16:03 UTC, merged